[package]
name = "wkfl"
version = "0.1.4"
description = "Tool to assist and automate my workflow"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.81", features = ["backtrace"] }
clap = { version = "4.5.3", features = ["derive"] }
crossterm = "0.27.0"
env_logger = "0.10.2"
fuzzy-matcher = "0.3.7"
git2 = "0.18.2"
home = "0.5.9"
log = "0.4.21"
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.12"
url = "2.5.0"
