[package]
name = "wkfl"
version = "0.1.2"
description = "Tool to assist and automate my workflow"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
clap = { version = "4.1.8", features = ["derive"] }
crossterm = "0.26.1"
env_logger = "0.10.0"
fuzzy-matcher = "0.3.7"
git2 = "0.16.1"
home = "0.5.5"
log = "0.4.17"
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.7.4"
