[package]
name = "wkfl"
version = "0.1.4"
description = "Tool to assist and automate my workflow"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.76", features = ["backtrace"] }
clap = { version = "4.4.11", features = ["derive"] }
crossterm = "0.27.0"
env_logger = "0.10.1"
fuzzy-matcher = "0.3.7"
git2 = "0.18.1"
home = "0.5.9"
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
toml = "0.8.8"
url = "2.5.0"
