[package]
name = "wkfl"
version = "0.1.4"
description = "Tool to assist and automate my workflow"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.93", features = ["backtrace"] }
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
env_logger = "0.11.5"
fuzzy-matcher = "0.3.7"
git2 = "0.19.0"
home = "0.5.9"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
url = "2.5.2"
