[package]
name = "wkfl"
version = "0.1.4"
description = "Tool to assist and automate my workflow"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.95", features = ["backtrace"] }
clap = { version = "4.5.23", features = ["derive"] }
crossterm = "0.28.1"
env_logger = "0.11.6"
fuzzy-matcher = "0.3.7"
git2 = "0.20.0"
home = "0.5.11"
log = "0.4.22"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
time = { version = "0.3.37", features = ["formatting", "macros", "parsing"] }
toml = "0.8.19"
ureq = { version = "2.12.1", features = ["json", "gzip"] }
url = "2.5.2"
