[package]
name = "wkfl"
version = "0.1.3"
description = "Tool to assist and automate my workflow"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
clap = { version = "4.3.4", features = ["derive"] }
crossterm = "0.26.1"
env_logger = "0.10.0"
fuzzy-matcher = "0.3.7"
git2 = "0.17.1"
home = "0.5.5"
log = "0.4.19"
serde = { version = "1.0.166", features = ["derive"] }
toml = "0.7.4"
url = "2.4.0"
