FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04

RUN sudo apt update && \
    sudo apt install --yes \
        libwebkit2gtk-4.1-dev \
        build-essential \
        curl \
        wget \
        file \
        libxdo-dev \
        libssl-dev \
        libayatana-appindicator3-dev \
        librsvg2-dev
