name: devenv

on:
  push:
    branches: [ "main" ]
    paths: [ "devenv/**" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: kdeal
        password: ${{ github.token }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:devenv"
        platforms: linux/amd64,linux/arm64, linux/arm/v7
        push: true
        tags: |
         ghcr.io/kdeal/devenv:latest
