name: wkfl release

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths: [ "devenv/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  recreate_latest_release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wkfl
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Create release
      run: |
        gh release delete wkfl/latest --yes || true
        git push origin :latest || true
        gh release create wkfl/latest
      env:
        GH_TOKEN: ${{ github.token }}

  build:
    name: ${{ matrix.job.target }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: aarch64-apple-darwin }
          - { target: aarch64-unknown-linux-musl }
          - { target: x86_64-unknown-linux-musl }
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wkfl
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.job.target }}
    - name: Build
      run: |
        cargo build --locked --release --target=${{ matrix.job.target }}
        mv target/release/wkfl wkfl-${{ matrix.job.target }}
    - name: Create release
      run: gh release upload wkfl/latest wkfl-${{ matrix.job.target }}
      env:
        GH_TOKEN: ${{ github.token }}
