name: wkfl test

on:
  push:
    branches: [ "main" ]
    paths: ["wkfl/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["wkfl/**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wkfl

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run format
      run: cargo fmt --check
    - name: Run clippy
      run: cargo clippy -- -Dwarnings
